version : "3"
services: 
    backend:
        image: tpiglcours  
        depends_on:
            - database 
        ports: 
            - "8080:8080"
        networks:
            - monreseau
    database:
        image: tpigldatabase
                
        ports:
            - "3306:3306"
        expose:
            - 3306
        networks:
            - monreseau 
networks:
    monreseau:                                         