version : "3"
services: 
    server2:
        image: tpiglnotes
        depends_on:
            -database
        ports:
            - "8082:8082"      
        networks:
            - monreseau 
    database:
        image: tpigldatabase
        
        ports:
            - "3306:3306"
        expose:
            - 3306
        networks:
            - monreseau  
      
networks:
    monreseau:                                         