version : "3"
services: 
    server:
        image: tpiglclasse
        depends_on:
            - database 
        ports:
            - "8081:8081"      
        networks:
            - monreseau 
    database:
        image: tpigldatabase
        
        ports:
            - "3306:3306"
        expose:
            - 3306
        networks:
            - monreseau   
      
networks:
    monreseau:                                         