version : "3"
services: 
    gestion-scolarite:
        image: tpiglfront
        depends_on:
            - backend
            - server
            - server2
            - mysql
        ports: 
            - "8083:8083"
        networks:
            - monreseau
    mysql:
        image: mysql:8.0.2
        environment:    
            MYSQL_HOST: localhost
            MYSQL_USER : root
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: tpigl
        ports:
            - "3306:3306"
        expose:
            - 3306
        networks:
            - monreseau    
                    
    backend:
        image: tpiglcours  
        ports: 
            - "8080:8080"
        networks:
            - monreseau
    server:
        image: tpiglclasse
        ports:
            - "8081:8081"      
        networks:
            - monreseau
    server2:
        image: tpiglnotes
        ports: 
            - "8082:8082"
        networks:
            - monreseau    
networks:
    monreseau:                                         